/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Lisnik234 (https://sketchfab.com/Lisnik234)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ibm-computer-113d95b2276945b6bb75c462bdbd5571
Title: IBM computer
*/

//import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
const GamerRoom =(props) => {
  const { nodes, materials } = useGLTF('/models/GamerRoom.glb')
  

  return (
    <group {...props} dispose={null}>
      <group position={[-4.253, 0.112, -0.439]} rotation={[0.012, -0.883, 0.003]} scale={0.757}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group position={[-3.042, 0.205, 0.253]} rotation={[0.022, 0, 0]} scale={0.104}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials.Kaybord}
        />
      </group>
      <group position={[-3.98, 0.153, 0.273]} rotation={[0.038, -1.374, 0.031]} scale={0.757}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_36.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_37.geometry}
          material={materials['Material.004']}
        />
      </group>
      <group position={[-1.307, 2.236, -4.435]} rotation={[1.57, -0.007, -1.577]} scale={0.757}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_39.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_40.geometry}
          material={materials['Material.004']}
        />
      </group>
      <group position={[-1.4, 2.236, -4.435]} rotation={[1.57, -0.007, -1.577]} scale={0.757}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_43.geometry}
          material={materials['Material.004']}
        />
      </group>
      <group position={[-1.486, 2.237, -4.434]} rotation={[1.57, -0.007, -1.577]} scale={0.757}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_45.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_46.geometry}
          material={materials['Material.004']}
        />
      </group>
      <group position={[-1.57, 2.238, -4.434]} rotation={[1.57, -0.007, -1.577]} scale={0.757}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_48.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_49.geometry}
          material={materials['Material.004']}
        />
      </group>
      <group position={[-1.856, 2.206, -4.433]} rotation={[1.57, -0.316, -1.577]} scale={0.757}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_51.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_52.geometry}
          material={materials['Material.004']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Material.006']}
        position={[0.04, 0.114, -1.911]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['Material.007']}
        position={[4.596, 0.189, -3.403]}
        rotation={[-Math.PI / 2, 0, 0.053]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials['Material.007']}
        position={[-1.374, 1.167, -2.507]}
        rotation={[-0.277, 0.019, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials['Material.007']}
        position={[2.917, 3.138, -4.009]}
        rotation={[-1.019, 1.541, 1.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials['Material.007']}
        position={[3.508, 0.114, -1.631]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials['Material.007']}
        position={[5.35, 0.149, 0.504]}
        rotation={[Math.PI / 2, 0, -0.382]}
        scale={0.887}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials['Material.007']}
        position={[4.563, 0.326, -3.374]}
        rotation={[Math.PI / 2, 0, -0.145]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials['Material.007']}
        position={[4.531, 0.462, -3.379]}
        rotation={[-Math.PI / 2, 0, -0.087]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.IMG_4494}
        position={[3.573, 0.118, -0.017]}
        rotation={[0, -0.314, 0]}
        scale={2.765}
      />
    sss
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials['Material.002']}
        position={[0, 1.207, -3.624]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials['Material.005']}
        position={[-3.43, 0.156, -2.184]}
        rotation={[0, 0, -1.573]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials['Material.007']}
        position={[-1.128, 2.528, -4.432]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials['Material.007']}
        position={[-2.18, 1.957, -3.121]}
      />
    </group>
  )
}


useGLTF.preload('/models/GamerRoom.glb');
export default GamerRoom;
