/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: subtixx (https://sketchfab.com/subtixx)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/pacman-17800bd2ae224ee281e43
Title: PacMan
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Pacman = (props) => {
  const { nodes, materials } = useGLTF('/models/pacman.glb'); // Ensure this path is correct

  // Modify the material's color
  if (materials.Object002_mtl) {
    materials.Object002_mtl.color.set('#D4A017'); // Darker yellow
  }

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object002_Object002_mtl_0.geometry}
          material={materials.Object002_mtl} // Use the modified material
          position={[0, 0.075, 1.996]}
        />
      </group>
    </group>
  );
};

// Preload the GLB file
useGLTF.preload('/models/pacman.glb'); // Ensure this path is correct

export default Pacman;
